Figaro.require_keys('SECRET_KEY_BASE', 'WEB_CONCURRENCY', 'MAX_THREADS',
                    'SENDGRID_USERNAME', 'SENDGRID_PASSWORD',
                    'DEVISE_SECRET_KEY', 'DEVISE_PEPPER', 'PAYPAL_CLIENT_ID',
                    'PAYPAL_CLIENT_SECRET')
